services:
  app:
    build: .
    container_name: fastapi_app
    expose:
      - "8000"
    restart: always

  nginx:
    image: nginx:latest
    container_name: fastapi_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
